apiVersion: v1
kind: ServiceAccount
metadata:
  name: yurt-operator-agent
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: yurt-operator-agent
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - configmaps
      - services
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - ""
      - apps
    resources:
      - daemonsets
      - deployments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - operator.openyurt.io
    resources:
      - yurtclusters
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - operator.openyurt.io
    resources:
      - yurtclusters/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: yurt-operator-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: yurt-operator-agent
subjects:
  - kind: ServiceAccount
    name: yurt-operator-agent
    namespace: kube-system
