//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 The OpenYurt Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentConfig) DeepCopyInto(out *ComponentConfig) {
	*out = *in
	out.ImageMeta = in.ImageMeta
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ExtraArgs != nil {
		in, out := &in.ExtraArgs, &out.ExtraArgs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentConfig.
func (in *ComponentConfig) DeepCopy() *ComponentConfig {
	if in == nil {
		return nil
	}
	out := new(ComponentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageMeta) DeepCopyInto(out *ImageMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageMeta.
func (in *ImageMeta) DeepCopy() *ImageMeta {
	if in == nil {
		return nil
	}
	out := new(ImageMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeCondition) DeepCopyInto(out *NodeCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeCondition.
func (in *NodeCondition) DeepCopy() *NodeCondition {
	if in == nil {
		return nil
	}
	out := new(NodeCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSet) DeepCopyInto(out *NodeSet) {
	*out = *in
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.NodeSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ExcludedNames != nil {
		in, out := &in.ExcludedNames, &out.ExcludedNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSet.
func (in *NodeSet) DeepCopy() *NodeSet {
	if in == nil {
		return nil
	}
	out := new(NodeSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YurtCluster) DeepCopyInto(out *YurtCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YurtCluster.
func (in *YurtCluster) DeepCopy() *YurtCluster {
	if in == nil {
		return nil
	}
	out := new(YurtCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *YurtCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YurtClusterList) DeepCopyInto(out *YurtClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]YurtCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YurtClusterList.
func (in *YurtClusterList) DeepCopy() *YurtClusterList {
	if in == nil {
		return nil
	}
	out := new(YurtClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *YurtClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YurtClusterSpec) DeepCopyInto(out *YurtClusterSpec) {
	*out = *in
	in.CloudNodes.DeepCopyInto(&out.CloudNodes)
	in.EdgeNodes.DeepCopyInto(&out.EdgeNodes)
	in.YurtHub.DeepCopyInto(&out.YurtHub)
	in.YurtTunnel.DeepCopyInto(&out.YurtTunnel)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YurtClusterSpec.
func (in *YurtClusterSpec) DeepCopy() *YurtClusterSpec {
	if in == nil {
		return nil
	}
	out := new(YurtClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YurtClusterStatus) DeepCopyInto(out *YurtClusterStatus) {
	*out = *in
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(YurtClusterStatusFailure)
		**out = **in
	}
	if in.FailureMessage != nil {
		in, out := &in.FailureMessage, &out.FailureMessage
		*out = new(string)
		**out = **in
	}
	if in.NodeConditions != nil {
		in, out := &in.NodeConditions, &out.NodeConditions
		*out = make(map[string]NodeCondition, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YurtClusterStatus.
func (in *YurtClusterStatus) DeepCopy() *YurtClusterStatus {
	if in == nil {
		return nil
	}
	out := new(YurtClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YurtHubSpec) DeepCopyInto(out *YurtHubSpec) {
	*out = *in
	in.Cloud.DeepCopyInto(&out.Cloud)
	in.Edge.DeepCopyInto(&out.Edge)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YurtHubSpec.
func (in *YurtHubSpec) DeepCopy() *YurtHubSpec {
	if in == nil {
		return nil
	}
	out := new(YurtHubSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YurtHubSpecTemplate) DeepCopyInto(out *YurtHubSpecTemplate) {
	*out = *in
	in.ComponentConfig.DeepCopyInto(&out.ComponentConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YurtHubSpecTemplate.
func (in *YurtHubSpecTemplate) DeepCopy() *YurtHubSpecTemplate {
	if in == nil {
		return nil
	}
	out := new(YurtHubSpecTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YurtTunnelAgentSpec) DeepCopyInto(out *YurtTunnelAgentSpec) {
	*out = *in
	in.ComponentConfig.DeepCopyInto(&out.ComponentConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YurtTunnelAgentSpec.
func (in *YurtTunnelAgentSpec) DeepCopy() *YurtTunnelAgentSpec {
	if in == nil {
		return nil
	}
	out := new(YurtTunnelAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YurtTunnelServerSpec) DeepCopyInto(out *YurtTunnelServerSpec) {
	*out = *in
	in.ComponentConfig.DeepCopyInto(&out.ComponentConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YurtTunnelServerSpec.
func (in *YurtTunnelServerSpec) DeepCopy() *YurtTunnelServerSpec {
	if in == nil {
		return nil
	}
	out := new(YurtTunnelServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YurtTunnelSpec) DeepCopyInto(out *YurtTunnelSpec) {
	*out = *in
	in.Server.DeepCopyInto(&out.Server)
	in.Agent.DeepCopyInto(&out.Agent)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YurtTunnelSpec.
func (in *YurtTunnelSpec) DeepCopy() *YurtTunnelSpec {
	if in == nil {
		return nil
	}
	out := new(YurtTunnelSpec)
	in.DeepCopyInto(out)
	return out
}
